### ISSUE TITLE
Headers don't get added in Dynamic renderer

### ISSUE THREAD

**Issue by lhotakj** [lhotakj/Mamlambo#2]
headers defined in `dynamic` renderer are ignored (works in `static`)
```
  - extension: ".pyhtml"
    serve: dynamic
    header:
      - custom-header: test
```
